from src.generated_code.asn1.GSMA.SGP_22.v1_0.python_gen.sgp22.sgp22 import RSPDefinitions

sgp_22_mapping = {
    'CertToBeUsed': RSPDefinitions.CertToBeUsed,
    'CertificateInfo': RSPDefinitions.CertificateInfo,
    'CurveSigningSupport': RSPDefinitions.CurveSigningSupport,
    'CurveVerificationSupport': RSPDefinitions.CurveVerificationSupport,
    'DPSigned1': RSPDefinitions.DPSigned1,
    'DeviceCapabilities': RSPDefinitions.DeviceCapabilities,
    'DeviceInfo': RSPDefinitions.DeviceInfo,
    'EIDPrefix': RSPDefinitions.EIDPrefix,
    'EUICCCapability': RSPDefinitions.EUICCCapability,
    'EUICCInfo1': RSPDefinitions.EUICCInfo1,
    'EUICCInfo2': RSPDefinitions.EUICCInfo2,
    'EUICCSigned1': RSPDefinitions.EUICCSigned1,
    'IconType': RSPDefinitions.IconType,
    'Octet1': RSPDefinitions.Octet1,
    'Octet16': RSPDefinitions.Octet16,
    'Octet32': RSPDefinitions.Octet32,
    'Octet8': RSPDefinitions.Octet8,
    'OctetTo16': RSPDefinitions.OctetTo16,
    'PrepareDownloadRequest': RSPDefinitions.PrepareDownloadRequest,
    'PrepareDownloadResponse': RSPDefinitions.PrepareDownloadResponse,
    'ProfileInfo': RSPDefinitions.ProfileInfo,
    'ProfileState': RSPDefinitions.ProfileState,
    'RSPCertificate': RSPDefinitions.RSPCertificate,
    'SetNicknameRequest': RSPDefinitions.SetNicknameRequest,
    'StoreMetadata': RSPDefinitions.StoreMetadata,
    'VersionType': RSPDefinitions.VersionType,
}