from src.generated_code.asn1.GSMA.SGP_22.v1_1.python_gen.sgp22_bf76.sgp22_bf76 import RSPDefinitions

sgp_22_mapping = {
    'CertToBeUsed': RSPDefinitions.CertToBeUsed,
    'CertificateInfo': RSPDefinitions.CertificateInfo,
    'CurveSigningSupport': RSPDefinitions.CurveSigningSupport,
    'CurveVandKASupport': RSPDefinitions.CurveVandKASupport,
    'DPSigned1': RSPDefinitions.DPSigned1,
    'DeviceCapabilities': RSPDefinitions.DeviceCapabilities,
    'DeviceInfo': RSPDefinitions.DeviceInfo,
    'EIDPrefix': RSPDefinitions.EIDPrefix,
    'EUICCCapability': RSPDefinitions.EUICCCapability,
    'EUICCInfo1': RSPDefinitions.EUICCInfo1,
    'EUICCInfo2': RSPDefinitions.EUICCInfo2,
    'EUICCSigned1': RSPDefinitions.EUICCSigned1,
    'IconType': RSPDefinitions.IconType,
    'Octet1': RSPDefinitions.Octet1,
    'Octet16': RSPDefinitions.Octet16,
    'Octet32': RSPDefinitions.Octet32,
    'Octet8': RSPDefinitions.Octet8,
    'OctetTo16': RSPDefinitions.OctetTo16,
    'PrepareDownloadRequest': RSPDefinitions.PrepareDownloadRequest,
    'PrepareDownloadResponse': RSPDefinitions.PrepareDownloadResponse,
    'ProfileInfo': RSPDefinitions.ProfileInfo,
    'ProfileState': RSPDefinitions.ProfileState,
    'ProprietaryTag': RSPDefinitions.ProprietaryTag,
    'RSPCertificate': RSPDefinitions.RSPCertificate,
    'RefArDo': RSPDefinitions.RefArDo,
    'SasSn': RSPDefinitions.SasSn,
    'SetNicknameRequest': RSPDefinitions.SetNicknameRequest,
    'StoreMetadataRequest': RSPDefinitions.StoreMetadataRequest,
    'StoreMetadataResponse': RSPDefinitions.StoreMetadataResponse,
    'VersionType': RSPDefinitions.VersionType,
    'id_rsp': RSPDefinitions.id_rsp,
    'id_rspExt': RSPDefinitions.id_rspExt,
    'id_rspRole': RSPDefinitions.id_rspRole,
    'id_rspRole_ci': RSPDefinitions.id_rspRole_ci,
    'id_rspRole_dp_pb': RSPDefinitions.id_rspRole_dp_pb,
    'id_rspRole_euicc': RSPDefinitions.id_rspRole_euicc,
    'id_rspRole_eum': RSPDefinitions.id_rspRole_eum,
    'id_rsp_sasSn': RSPDefinitions.id_rsp_sasSn,
}