import os


class Constants:
    STR_CONVERSION_MODE = 'Conversion Mode'
    DEFAULT_OUTPUT_FOLDER = os.sep.join([os.pardir, os.pardir, 'UserData'])
    MAX_HEADING_LENGTH = 120
    LENGTH_RESERVE_LIST_REMARKS = 6
    DEFAULT_REMARKS_MAX_LENGTH = MAX_HEADING_LENGTH - LENGTH_RESERVE_LIST_REMARKS
    DEFAULT_TRIM_STRING = '...'
    DEFAULT_TRIM_STRING_LENGTH = len(DEFAULT_TRIM_STRING)
