class Formats:
    ASN1 = 'asn1'
    DER = 'der'
    DER_64 = 'der_with_base64'
    DER_WS = 'der_ws'
    BER = 'ber'
    BER_64 = 'ber_with_base64'
    BER_WS = 'ber_ws'
    GET_VAL = 'get_val',
    GET_VAL_PATHS = 'get_val_paths'
    GET_PROTO = 'get_proto'
    JSON = 'json'
    APER = 'aper'
    CER = 'cer'
    CER_WS = 'cer_ws'
    JER = 'jer'
    UPER = 'uper'
