class Keys:
    INPUT = 'input'
    INPUT_FORMAT = 'input_format'
    INPUT_DATA = 'input_data'
    INPUT_FILE = 'input_file'
    INPUT_LIST = 'input_list'
    INPUT_DIR = 'input_dir'
    INPUT_YML = 'input_yml'
    INPUT_MODES_HIERARCHY = 'input_modes_hierarchy'

    OUTPUT = 'output'
    OUTPUT_FORMAT = 'output_format'
    OUTPUT_DATA = 'output_data'
    OUTPUT_FILE = 'output_file'
    EXPORT_FILE = 'export_file'
    RE_OUTPUT_FILE = 're_output_file'
    OUTPUT_FILE_NAME_KEYWORD = 'output_file_name_keyword'

    RAW_DATA = 'raw_data'
    RE_PARSED_DATA = 're_parsed_data'
    ASN1_ELEMENT = 'asn1_element'
    INFO = 'info'

    PRINT_INPUT = 'print_input'
    PRINT_OUTPUT = 'print_output'
    PRINT_INFO = 'print_info'
    RE_PARSE_OUTPUT = 're_parse_output'
    REMARKS_LIST = 'remarks_list'
    REMARKS_LIST_GENERATED = 'remarks_list_generated'

    OUTPUT_VERSION = 'output_version'
    #
    PYTHON = 'Python'
    SGP22 = 'SGP22'
    ASN1PLAY = 'asn1play'
    EUICC_PROFILE_PACKAGE = 'eUICC_Profile_Package'
    PYTHONHELPERS = 'pythonHelpers'
    TIME_STAMP = 'time_stamp'
